
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

  app:
    environment:
      MAILER_DSN: smtp://mailer:1025
      MAILER_FROM: no-reply@snipnote.local
    depends_on:
      mailer:
        condition: service_started

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
